apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  namespace: webapps
  labels:
    app: reactapp
spec:
  replicas: : : 3 
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactserver
        image: santoshahirwar/reactstatic_test:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  namespace: webapps
spec:
  selector:
    app: reactapp
  type: LoadBalancer   # if on cloud (AWS/GCP/Azure) or using MetalLB
  ports:
  - name: http
    protocol: TCP
    port: 80           # external port (user will access this)
    targetPort: 80     # container port

